package com.example.animatelyapp.ui.theme
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight

val primaryLight = Color(0xFF503C96)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE8DDFF)
val onPrimaryContainerLight = Color(0xFF1F1048)
val secondaryLight = Color(0xFF615B71)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE7DEF8)
val onSecondaryContainerLight = Color(0xFF1D192B)
val tertiaryLight = Color(0xFF7D5261)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD9E3)
val onTertiaryContainerLight = Color(0xFF31101E)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFDF7FF)
val onBackgroundLight = Color(0xFF1C1B20)
val surfaceLight = Color(0xFFFDF7FF)
val onSurfaceLight = Color(0xFF1C1B20)
val surfaceVariantLight = Color(0xFFE6E0EC)
val onSurfaceVariantLight = Color(0xFF48454E)
val outlineLight = Color(0xFF79757F)
val outlineVariantLight = Color(0xFFCAC4CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF322F35)
val inverseOnSurfaceLight = Color(0xFFF5EFF7)
val inversePrimaryLight = Color(0xFFCEBDFF)


val primaryDark = Color(0xFFCEBDFF)
val onPrimaryDark = Color(0xFF35275E)
val primaryContainerDark = Color(0xFF4B3E76)
val onPrimaryContainerDark = Color(0xFFE8DDFF)
val secondaryDark = Color(0xFFCBC3DC)
val onSecondaryDark = Color(0xFF322E41)
val secondaryContainerDark = Color(0xFF494458)
val onSecondaryContainerDark = Color(0xFFE7DEF8)
val tertiaryDark = Color(0xFFEFB8C9)
val onTertiaryDark = Color(0xFF492533)
val tertiaryContainerDark = Color(0xFF633B49)
val onTertiaryContainerDark = Color(0xFFFFD9E3)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF141318)
val onBackgroundDark = Color(0xFFE6E1E9)
val surfaceDark = Color(0xFF141318)
val onSurfaceDark = Color(0xFFE6E1E9)
val surfaceVariantDark = Color(0xFF48454E)
val onSurfaceVariantDark = Color(0xFFCAC4CF)
val outlineDark = Color(0xFF938F99)
val outlineVariantDark = Color(0xFF48454E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE6E1E9)
val inverseOnSurfaceDark = Color(0xFF322F35)
val inversePrimaryDark = Color(0xFF64568F)



val orange = Color(0xFFE68A3F)
val deepOrange = Color(0xFFE48C3F)
val lightOrange = Color(0xFFf9E7D7)
val lightGreen = Color(0xFFDAEFDF)
val dirtyWhite = Color(0xFFFAFAFA)
val grey = Color(0xFFF8F8F8)
val green = Color(0xFF71C496)
val greyOp = Color(0xFF172332)
val paleBlue = Color(0xFF6F8DB0)
val statusGray = Color(0xFFECECEC)
